### ISSUE TITLE
Use <?php echo instead of <?=

### ISSUE THREAD

**Issue by xPaw** [Panthera-Framework/raintpl4#11]
Some commit changed echo to a short `<?=` tag, and this prevents the optimization that removes extra `?><?php` tags.

**Comment by webnull** [comment]
So, we could add optimizations also for <?= :smile:

**Comment by xPaw** [comment]
I'm not sure there's any real reason to sticking with `<?=`

**Comment by webnull** [comment]
Project is not compatible with PHP older than PHP 5.4, so there is no any problem with that tag.
From PHP 5.4 this syntax is always available regardless of settings.

http://php.net/manual/en/language.basic-syntax.phptags.php

**Comment by webnull** [comment]
Also there is no real reason to change from short syntax to regular syntax. The argument is that the code is more simple, shorten, and there are less tokens to parse for PHP parser.

**Comment by xPaw** [comment]
> The argument is that the code is more simple, shorten, and there are less tokens to parse for PHP parser.

I don't think that matters in a compiled template, that's a very minor thing to be concerned about.
