### ISSUE TITLE
Usage of comment tags.

### ISSUE THREAD

**Issue by lnxmen** [Panthera-Framework/raintpl4#15]
What are the rules of using comment tags?
Now, we may tell parser that comment is closed using other tag than was used to start.
Example: `{*} comment {/ignore}`

Should we parse code in this way?
Maybe closing comments only with the same tag would enhance capabilities? We would be able to comment blocks of code that already contains comments.

**Comment by webnull** [comment]
Yes, why not. The {*} and {ignore} is same tag. The second one is just an **alias**, maybe it looks weird but makes sense in a real code anyway.

**Comment by webnull** [comment]
Regarding:

```
Maybe closing comments only with the same tag would enhance capabilities? We would be able to comment blocks of code that already contains comments.
```

Yes, sure - it would be an additional capability, but... it's not neccessary, and it would be difficult to implement.

**Comment by lnxmen** [comment]
Okay, I just wasn't sure if this way is correct (despite my adding this code as a test). Thanks.
