### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by webnull** [Panthera-Framework/raintpl4#17]
We need a `CoffeeScript` plugin that would compile embedded and externally linked CoffeeScript code into pure Javascript.

```html
<script type="text/coffeescript">
console.log "This was written from Coffescript"
</script>
```

Result:
```html
<script type="text/javascript">
console.log('This was written from Coffeescript');
</script>
```

And externally linked:
```html
<script type="text/coffeescript" src="test.js" source="test.coffee"></script>
``

Result:
```html
<script type="text/javascript" src="test.js"></script>
```

**Comment by lnxmen** [comment]
I have already created `plugins/CoffeeScript` branch for this purpose.
https://github.com/Panthera-Framework/raintpl4/tree/plugins/CoffeeScript

**Comment by lnxmen** [comment]
CoffeeScript compiler automatically takes destination filepath (assume `source.coffee`) as `source.js`.

**Comment by webnull** [comment]
Hmm, after some research I found out that it would be very easy to add Dart language support.

https://www.dartlang.org/tools/dart2js/

The same plugin could do this, just like in CSSLess.

**Comment by webnull** [comment]
All implemented.

Languages/compilers could be easily added in "CoffeeScript.compilers" configuration key, example:

```php
array(
            // CoffeeScript, ofically this is supported
            'text/coffeescript' => array(
                'executable' => 'coffee',
                'stdinParams' => '-sp',
                'fileParams' => '-p %s',
            ),

            // Google Dart, just an example how to add a custom language and compiler here # dart2js --out=test.js test.dart
            'text/dart' => array(
                'executable' => 'dart2js',
                'stdinParams' => false, // dart2js does not support read from stdin
                'fileParams' => '--out=%d %s',
            ),
        )
```
