### ISSUE TITLE
{continue} and {break}

### ISSUE THREAD

**Issue by webnull** [Panthera-Framework/raintpl4#2]
Please write {continue} and {break} testcases.

Example:
```html
{foreach from="$array" as $k => $v}
    {if $k == 'this is a test'}
        {break}
    {/if}
{/foreach}
```

**Comment by webnull** [comment]
Please also make a check for opened loops - $this->tagData['loop'] should contain that informations.

If we are doing {break 2} then we have to check if there are two loops opened, there is a such counter avaliable already in every tag's tagData entry.

**Comment by lnxmen** [comment]
Your example is invalid:
```{foreach from="$array" as $k => $v}```.
Error: ```(syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'```)
We need to fix this - actually, I have added appropiate testcases.

**Comment by webnull** [comment]
Could you check if this works?

```html
{foreach from="$array" as $du => $pa}
    {$du} => {$pa}
{/foreach}
``

**Comment by lnxmen** [comment]
Surely, give me a minute.

**Comment by webnull** [comment]
Yes, but something says me that its incorrectly cutting out two-byte named variables.

**Comment by lnxmen** [comment]
```
/**
     * Testcase for {foreach from="$array" as $keyName => $itemValue}
     *
     * <code>{foreach from="$arrayVariable" as $keyName => $itemValue}{$keyName} => {$itemValue}{/foreach}</code>
     * <expects>value1</expects>
     *
     * @author Mateusz Warzyński <lxnmen@gmail.com>
     */
    public function testForeachAsKeyValue()
    {
        $this->setupRainTPL4();

        $this->engine->assign('arrayVariable', array('key1' => 'value1'));
        $this->autoAssertEquals();
    }
```

PHPUnit error:
```
PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /tmp/d42c2528dc0d7eca128822833bf94654.s.rtpl.php on line 1
```
Compiled template:
```
foreach($newVar as $keyName => $itemValu => $keyName)
```

**Comment by webnull** [comment]
Okay, I know what is going on. I will fix that. It's just a mistake in a strpos() position or length calculation. I know this code good.
