### ISSUE TITLE
Don't parse javascript code.

### ISSUE THREAD

**Issue by lnxmen** [Panthera-Framework/raintpl4#21]
RainTPL4 should not parse javascript code in case of parsing unknown tags which are correct.

For instance:
```
$("#id").animate({opacity:"show"}, 400); // {opacity} will not work
```

I know, we might force keeping javascript away from template files and prevent from writing unclean code.
What should we do?

**Comment by webnull** [comment]
I don't know what we could do in this case.

I suggest to change this code for a moment for:
```html
$("#id").animate({ opacity:"show" }, 400); // {opacity} will not work
```

**Comment by webnull** [comment]
Currently won't fix.
