### ISSUE TITLE
Auto escape strings feature

### ISSUE THREAD

**Issue by markkimsal** [Panthera-Framework/raintpl4#28]
I couldn't verify that raintpl4 auto escapes strings with htmlspecialchars like 3 does.  It seems like there will be a generic filter feature, or that there is one for {block} and {print} tags, but I couldn't get it to work.  On the examples-all page I'm seeing the bad JS alert, when it should be escaped down to &gt; etc.

Is auto escaping on the roadmap?  Am I doing it wrong?  Auto-escaping is the no. 1 reason I use a template engine, so I had to downgrade back to 3 for the time being.

**Comment by lnxmen** [comment]
It seems that currently RainTPL4 does not escape variable strings. At least, my just cloned version also shows bad javascript alerts.

Actually, simple trick to escape all values is to add this condition in line 797 before `return $html` in `library/Rain/Tpl/Parser.php` file.
```
if ($this->config['auto_escape'] && $escape)
            $html = "htmlspecialchars( $html, ENT_COMPAT, '" . $this->config['charset'] . "', FALSE )";
```

Of course, it won't solve the problem as after this change {autoescape} tag won't be implemented at all. There is only a concept of how would it work / what would be useful.

I have done only minor changes to this project, therefore I am not able to provide fully correct and relevant answer for your question.
@webnull, would you mind checking this issue?

Also burn in mind that RainTPL4 is obviously unstable, so I advice not to use it (for now) in productive mode.
_______________________
Yes, {autoescape} tag is necessary and should be implemented.
No, you aren't doing it wrong. Rewritten examples should work out-of-the-box.

**Comment by webnull** [comment]
Could you describe what do you want exactly to get?
Any examples how you imagine it should work?
I think I could implement it but please tell me how it should look for you.
Of course we could put a parser setting that could turn on/off autoescaping.

**Comment by markkimsal** [comment]
I liked the way rain3 did it with the config auto_escape.  The number 1 reason I use a templating system is to avoid having <?php echo htmlspecialchars( $var ENT_QUOTES, 'UTF-8');?> everywhere in my templates.  Number 2 reason would probably be concise loop syntax

But, if autoescaping is on globally, then there is a requirement to turn it off with {autoescape="off"} or a filter like {$var|raw}.

I'm not sure what the state of rain4 is, but when I hit example-all.php (which seems to be updated to v4 semantics) I can see the unsafe JS alert.

**Comment by webnull** [comment]
Ok, I will work on it. Sounds easy.

**Comment by webnull** [comment]
Made some progress on separate branch.

**Comment by webnull** [comment]
Implemented. Only missing unit tests that I will add propably tommorow. Please check it by yourself. Or if you could please add some unit tests.

**Comment by webnull** [comment]
Feature implemented with unit tests and merged to master.

**Comment by markkimsal** [comment]
Thank you

**Comment by lnxmen** [comment]
Autoescape test on HHVM fails.
https://travis-ci.org/Panthera-Framework/raintpl4/jobs/87539787

**Comment by webnull** [comment]
You could investigate this ;-)
